use std::path::PathBuf;

use clay_layout::{
    Clay, Declaration, fixed,
    render_commands::RenderCommandConfig,
    text::{TextConfig, TextElementConfig},
};

use crate::{
    geometry::{Rect, Vector},
    render::{
        Border, BorderRadius, Color,
        rect::{RectRenderer, ScissorRegion},
        text::TextRenderer,
    },
    shader::Shader,
};

pub struct ClayRenderer {
    rect_r: RectRenderer,
    text_r: TextRenderer,
    clay: Clay,
    scissor_stack: Vec<ScissorRegion>,
}

struct Dummy {}

impl ClayRenderer {
    pub fn new(
        rect_shader: Shader,
        text_shader: Shader,
        screen_width: f32,
        screen_height: f32,
    ) -> Self {
        Self {
            rect_r: RectRenderer::new(rect_shader),
            text_r: TextRenderer::new(
                text_shader,
                &PathBuf::from("./assets/fonts/LiberationMono.ttf"),
            )
            .unwrap(),
            clay: Clay::new((screen_width, screen_height).into()),
            scissor_stack: vec![],
        }
    }

    pub fn draw(&mut self) {
        let mut clay = self.clay.begin::<(), ()>();

        // Add text
        clay.with(
            &Declaration::new()
                .id(clay.id("red_rectangle"))
                .layout()
                .width(fixed!(50.))
                .height(fixed!(50.))
                .end()
                .corner_radius()
                .all(5.)
                .end()
                .background_color((0xFF, 0x00, 0x00).into())
                .border()
                .all_directions(10)
                .color((0x00, 0xFF, 0x00).into())
                .end(),
            |parent| {
                parent.text(
                    "Hello, world!",
                    TextConfig::new()
                        .font_size(16)
                        .color((0xff, 0xff, 0xff).into())
                        .end(),
                )
            },
        );

        let render_commands = clay.end();

        for command in render_commands {
            match &command.config {
                RenderCommandConfig::None() => {}
                RenderCommandConfig::Rectangle(rectangle) => {
                    self.rect_r.draw(
                        command.bounding_box.into(),
                        rectangle.color.into(),
                        Color::default(),
                        Border {
                            thickness: 0.,
                            radius: rectangle.corner_radii.clone().into(),
                        },
                        1.0,
                    );
                }
                RenderCommandConfig::Border(border) => {
                    self.rect_r.draw(
                        command.bounding_box.into(),
                        Color::default(),
                        border.color.into(),
                        Border {
                            // I dont want variable border width around a box
                            thickness: border.width.top as f32,
                            radius: border.corner_radii.clone().into(),
                        },
                        1.0,
                    );
                }
                RenderCommandConfig::Text(text) => {
                    self.text_r.draw_text(
                        text.text,
                        Vector {
                            x: command.bounding_box.x,
                            y: command.bounding_box.y + command.bounding_box.height * 0.8,
                        },
                        text.font_size.into(),
                        1.0,
                        text.color.into(),
                    );
                }
                RenderCommandConfig::Image(image) => todo!(),
                RenderCommandConfig::ScissorStart() => todo!(),
                RenderCommandConfig::ScissorEnd() => todo!(),
                RenderCommandConfig::Custom(custom) => todo!(),
            }
            println!("Id of the element: {}", command.id); // Note: Ids are in fact numbers generated by Clay
            println!("Bounding box: {:?}", command.bounding_box);
            println!("Type and config: {:?}", command.config);
        }
    }
}
